# This is a dummy configuration file that *does not run any test*.

platform:
    - x64

install:
    - "echo 'Not installing anything.'"

build: false

test_script:
    - "echo 'Not testing anything.'"
