version: "{branch} (#{build})"

image:
  - Visual Studio 2015
  - Visual Studio 2019

environment:
  DEBUG: 1
  WARNINGS: 1
  matrix:
    - STANDALONE: 1
      SEPARATE_COMPILATION: 1
      MINGW: 1
    - STANDALONE: 1
      HEADER_ONLY: 1
      MSVC: 1
    - STANDALONE: 1
      SEPARATE_COMPILATION: 1
      MSVC: 1
    - STANDALONE: 1
      CXXLATEST: 1
      MSVC: 1

for:
  -
    matrix:
      only:
        - image: Visual Studio 2015
          MINGW: 1
    environment:
      BOOSTDIR: C:/Libraries/boost_1_63_0
    build_script:
      - PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\msys64\usr\bin;%PATH%
      - cd asio\src
      - mingw32-make -f Makefile.mgw
      - mingw32-make -f Makefile.mgw check
  -
    matrix:
      only:
        - image: Visual Studio 2019
    environment:
      BOOSTDIR: C:\Libraries\boost_1_71_0
      _WIN32_WINNT: 0x0601
#      _WIN32_WINNT: 0x0A00
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
      - cd asio\src
      - nmake -f Makefile.msc
      - nmake -f Makefile.msc check

matrix:
  exclude:
    - image: Visual Studio 2015
      MSVC: 1
    - image: Visual Studio 2019
      MINGW: 1
