name: linux

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler: [g++-10, g++-11, clang++-13]
        cxx-std: ['c++17', 'c++20']
        separate-compilation: ['']
        #separate-compilation: ['', '--enable-separate-compilation']
        optim-level: ['-O0']
        no-deprecated: ['']
        select-reactor: ['', '-DASIO_DISABLE_EPOLL']
        handler-tracking: ['']
        #exclude:
          # Older compilers don't support newer std variants
          #- compiler: g++-11
          #  cxx-std: c++2a
          # Trim builds that use separate compilation
          #- compiler: g++-9
          #  separate-compilation: --enable-separate-compilation
        include:
          #
          # Linux / g++-10 / -O0 / standalone / handler tracking
          #
          - os: ubuntu-20.04
            compiler: g++-10
            cxx-std: c++17
            optim-level: -O0
            handler-tracking: -DASIO_ENABLE_HANDLER_TRACKING
          #
          # Linux / g++-10 -std=c++20 -fcoroutines / -O2 / standalone
          #
          - os: ubuntu-20.04
            compiler: g++-10
            cxx-std: c++20 -fcoroutines
            optim-level: -O2
          #
          # Linux / clang++-13 -std=c++20 / -O2 / standalone
          #
          - os: ubuntu-20.04
            compiler: clang++-13
            cxx-std: c++20
            optim-level: -O2

    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.compiler }}
      CXXFLAGS: -std=${{ matrix.cxx-std }} ${{ matrix.optim-level }} -Wall -Wextra ${{ matrix.no-deprecated }} ${{ matrix.select-reactor }} ${{ matrix.handler-tracking }}
    steps:
    - uses: actions/checkout@v3

    - name: Init Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y lsb-release wget software-properties-common gnupg

    - name: Install GCC 10
      run: |
        sudo apt-get install -y g++-10 libstdc++-10-dev
      if: ${{ matrix.compiler == 'g++-10' }}

    - name: Install GCC 11
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install -y g++-11 libstdc++-11-dev
      if: ${{ matrix.compiler == 'g++-11' }}

    - name: Install Clang 13
      run: |
        sudo apt-get install -y g++-10 libstdc++-10-dev
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/  llvm-toolchain-$(lsb_release -cs)-13 main"
        sudo apt-get install -y clang-13 libomp-13-dev libc++-13-dev libc++abi-13-dev
      if: ${{ matrix.compiler == 'clang++-13' }}

    - name: Configure
      working-directory: asio
      run: |
        ./autogen.sh
        ./configure ${{ matrix.separate-compilation }}
    - name: Build And Test
      working-directory: asio
      run: make && make check
