name: macos

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        cxx-std: ['c++20']
        separate-compilation: ['']
        #separate-compilation: ['', '--enable-separate-compilation']
        optim-level: ['-O0', '-O3']
        select-reactor: ['']
        handler-tracking: ['']
        include:
          #
          # macos-12 / -O0 / handler tracking
          #
          - os: macos-12
            cxx-std: c++20
            optim-level: -O0
            handler-tracking: -DASIO_ENABLE_HANDLER_TRACKING
          #
          # macos-12 / -O0 / without kqueue
          #
          - os: macos-12
            cxx-std: c++20
            optim-level: -O0
            select-reactor: -DASIO_DISABLE_KQUEUE

    runs-on: ${{ matrix.os }}
    env:
      CXX: clang++
      CXXFLAGS: -std=${{ matrix.cxx-std }} ${{ matrix.optim-level }} -Wall -Wextra ${{ matrix.select-reactor }} ${{ matrix.handler-tracking }}
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_13.3.1.app"
    - name: Install autotools
      run: brew install automake
    # Корутины отключены из-за ошибки:
    #   fatal error: error in backend: Cannot select: intrinsic %llvm.coro.size
    #   clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
    #   Apple clang version 13.1.6 (clang-1316.0.21.2.3)
    - name: Configure
      working-directory: asio
      run: |
        sed -i .bak 's/HAVE_COROUTINES=yes/HAVE_COROUTINES=no/' configure.ac
        rm configure.ac.bak
        ./autogen.sh
        ./configure ${{ matrix.separate-compilation }}
    - name: Build And Test
      working-directory: asio
      run: make && make check
